### ISSUE TITLE
Hot reload functionality

### ISSUE THREAD

**Issue by Aashiq-Otp** [appblocks-hub/BB-CLI#11]
## Feature request

**What is the expected behavior?**
CLI should automatically restart the app when any change is made into the code.

**What is the current behavior?**
user need to manually run `bb stop` and `bb start <app_name>` to see changes in effect

**Comment by that-coder** [comment]
Hi @Aashiq-Otp 
Thanks for hacking using our CLI. We will add this feature to CLI soon and will keep you posted.

**Comment by that-coder** [comment]
hmr is added in latest version. @Aashiq-Otp
