### ISSUE TITLE
issue with loading .env files

### ISSUE THREAD

**Issue by Aashiq-Otp** [appblocks-hub/BB-CLI#12]
#### Issue description
 could not load env file inside the standalone app folder.The env files which is in container folder (.env.functions & .env.view) can be accessed but only with providing a full relative path in 'dotenv' configuration 

#### Steps to reproduce the issue

1.1.  create a `.env` file inside the standalone app folder
1.2.  try to access it with 'dotenv' like   `const env = dotenv.config({ path:'.env' })` //undefined
2.1  try with `.env.functions ` or `.env.view`     like  `const env = dotenv.config({ path:'.env.functions' })`  //undefined
2.2. try again with providing relative path like  `const env = dotenv.config({ path:'../.env.functions' })` //works

#### What's the expected result?

- env should be loaded easily without providing full relative path either from the standalone app folder or from the container app

**Comment by that-coder** [comment]
We will fix the issue in next release. Thanks for reporting.

**Comment by that-coder** [comment]
@Aashiq-Otp this is fixed. closing the issue
